apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
        version: v1
    spec:
      containers:
      - name: userapi
        image: mariecb/userapi:latest
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "449217"
        - name: MYSQL_DATABASE
          value: "lab"