#This file defines a Kubernetes deployment for the userapi application version 2.
# It specifies the deployment configuration, including the number of replicas, selector labels, and container specifications

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
      version: v2
  template:
    metadata:
      labels:
        app: userapi
        version: v2
    spec:
      containers:
        - name: userapi
          image: mariecb/userapi:latest 
          ports:
            - containerPort: 3000
