#This file defines a Kubernetes service for the userapi application.
# It exposes the userapi application on port 3000 and uses NodePort to allow external access. 

apiVersion: v1
kind: Service
metadata:
  name: userapi-service
spec:
  selector:
    app: userapi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort