apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: userapi
spec:
  hosts:
    - userapi-service
  http:
    - route:
        - destination:
            host: userapi-service
            subset: v1
          weight: 50
        - destination:
            host: userapi-service
            subset: v2
          weight: 50