# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: 449217
          MYSQL_DATABASE: lab
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysql -h127.0.0.1 -uroot -p449217 -e "USE lab;" ; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done
      - name: Install dependencies
        run: npm install
      - name: Create users table
        run: |
          mysql -h127.0.0.1 -uroot -p449217 lab -e "
          CREATE TABLE IF NOT EXISTS users (
            username VARCHAR(255) PRIMARY KEY,
            firstname VARCHAR(255),
            lastname VARCHAR(255)
            );
          "
      - name: Run tests
        run: npm test
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: 449217
          MYSQL_DATABASE: lab
